### ISSUE TITLE
Exit Code 1: Error on system DNS setting

### ISSUE THREAD

**Issue by fakkoweb** [8bitgeek/OpenNIC-Wizard#1]
In "System" tab it always say syntax of the name of the file, folder or volume is incorrect (in my case is written in italian). Error 1 also appears in the log after saying "Begin applying updated...".
No resolver address appears in the tooltip.

Run application and installer as Admin with no results.

**Comment by 8bitgeek** [comment]
I am understanding that you are running on Windows OS, in Italian Language?
Yes, it's possible that perhaps there's a path or something that is different in Italian Language.
I would suspect it's in here:
https://github.com/8bitgeek/OpenNIC-Wizard/blob/master/server/opennicsystem.cpp
#if defined(Q_OS_WIN32) 
These are the Windows-specfic system calls. Probably it's the OpenNICSystem::updateResolver(...) method.
Probably it's this command-line string that is different in Italian?:
	arguments << "interface" << "ip" << "set" << "dns" << "Local Area Connection" << "static" << resolver.toString();
--Mike

**Comment by jmengelle** [comment]
i have the same issue on windows 10 French. 
But the language is not the problem here. 

If i run the command line : 
`netsh interface show interface`

It show me 2 interface name: 
- Ethernet
- Wi-Fi
Look like it's the norm now. 

So there is no "Local Area Connection" interface, and it fail to add/update. 

There are chunck of code on the web to get it dynamically:
like [https://stackoverflow.com/questions/17288908/get-network-interface-name-from-ipv4-address](url)
or [https://gist.github.com/yoggy/1241986](url)

Unfortunately i'm not a CPP developer, so i can't even update & recompile easily. 
Do you mind doing it @8bitgeek  ?

**Comment by temp10min** [comment]
Same issue here. 
I rename my interfaces to the network adapter name, so there is no "Local Area Connection" interface.
System is english XP Pro SP3

**Comment by 8bitgeek** [comment]
I believe that these will be resolved here https://github.com/8bitgeek/OpenNIC-Wizard/issues/9
